#!/bin/bash
if [ -z $1 ]
then
	REPEAT=5
else
	REPEAT=$1
fi

while [ 1 ]
do
	clear
	printf "Refreshing stats every $REPEAT seconds.../nPress CTRL+C to exit/n"
	if [ -z $1 ]
	then
		printf "Tip: You can use $1 (1st parameter) to set refresh delay/n"
	fi
	printf "/nStatus:           `cat /sys/class/power_supply/battery/status`/n"
	printf "Percentage:       `cat /sys/class/power_supply/battery/capacity`%/n"
	printf "Maximum capacity: $((`cat /sys/class/power_supply/battery/voltage_max_design`/1000))mV/n"
	printf "Capacity now:     $((`cat /sys/class/power_supply/battery/voltage_now`/1000))mV/n"
	printf "Health:           `cat /sys/class/power_supply/battery/health`/n"
	printf "Model name:       `cat /sys/class/power_supply/battery/model_name`/n"
	printf "Technology:       `cat /sys/class/power_supply/battery/technology`/n"
	printf "Temperature:      $((`cat /sys/class/power_supply/battery/temp`/10))°C"
	sleep $REPEAT
done
